/**
 * Generated by typeshare 1.13.4
 */

package com.islamic.zakat

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/// Represents the semantic operation performed in a calculation step.
@Serializable
enum class Operation(val string: String) {
	@SerialName("initial")
	Initial("initial"),
	@SerialName("add")
	Add("add"),
	@SerialName("subtract")
	Subtract("subtract"),
	@SerialName("multiply")
	Multiply("multiply"),
	@SerialName("divide")
	Divide("divide"),
	@SerialName("compare")
	Compare("compare"),
	@SerialName("rate")
	Rate("rate"),
	@SerialName("result")
	Result("result"),
	@SerialName("info")
	Info("info"),
}

/// Represents a single step in the Zakat calculation process.
/// 
/// This struct provides transparency into how the final Zakat amount was derived,
/// enabling users to understand and verify each step of the calculation.
@Serializable
data class CalculationStep (
	/// The Fluent ID (e.g., "step-net-assets").
	val key: String,
	/// Fallback English text.
	val description: String,
	/// The value at this step (if applicable).
	val amount: string? = null,
	/// The semantic operation type.
	val operation: Operation
)

/// A collection of calculation steps that can be displayed or serialized.
typealias CalculationTrace = List<CalculationStep>

/// Structured warning codes for localization support.
/// 
/// Frontends can use these codes to provide localized warning messages
/// instead of hardcoded English strings.
@Serializable
sealed class WarningCode {
	/// Net assets were negative and clamped to zero.
	@Serializable
	@SerialName("NEGATIVE_ASSETS_CLAMPED")
	object NegativeAssetsClamped: WarningCode()
	/// Expenses were ignored when using the Gross calculation method.
	@Serializable
	@SerialName("GROSS_METHOD_EXPENSES_IGNORED")
	object GrossMethodExpensesIgnored: WarningCode()
	/// Livestock count is below minimum threshold for Zakat.
	@Serializable
	@SerialName("LIVESTOCK_BELOW_NISAB")
	object LivestockBelowNisab: WarningCode()
	/// Gold or silver weight is below minimum threshold.
	@Serializable
	@SerialName("METAL_BELOW_NISAB")
	object MetalBelowNisab: WarningCode()
	/// Price data may be stale or unavailable.
	@Serializable
	@SerialName("PRICE_DATA_STALE")
	object PriceDataStale: WarningCode()
	/// Hawl period not yet satisfied.
	@Serializable
	@SerialName("HAWL_NOT_MET")
	object HawlNotMet: WarningCode()
	/// Partial calculation due to missing data.
	@Serializable
	@SerialName("PARTIAL_CALCULATION")
	object PartialCalculation: WarningCode()
	/// Currency conversion applied.
	@Serializable
	@SerialName("CURRENCY_CONVERSION_APPLIED")
	object CurrencyConversionApplied: WarningCode()
	/// Other warning with custom code.
	@Serializable
	@SerialName("OTHER")
	data class Other(val content: String): WarningCode()
}

/// A structured warning with code, message, and optional details.
/// 
/// This enables frontends to:
/// - Localize warning messages using the `code` field
/// - Display English fallback via `message` field
/// - Access additional context through `details`
@Serializable
data class CalculationWarning (
	/// Structured warning code for programmatic handling and i18n.
	val code: WarningCode,
	/// Human-readable fallback message in English.
	val message: String
)

/// Generic asset type for user-defined assets.
/// Allows users to create custom zakatable assets with custom rates and thresholds.
@Serializable
data class CustomAsset (
	/// Unique identifier for this asset.
	val id: string,
	/// Human-readable label for this asset.
	val label: String,
	/// Total value of the asset.
	val value: string,
	/// Zakat rate to apply (e.g., 0.025 for 2.5%).
	val rate: string,
	/// Minimum threshold for Zakat obligation.
	val nisabThreshold: string,
	/// Whether the Hawl (one lunar year) has been satisfied.
	val hawlSatisfied: Boolean,
	/// Name of the wealth type for categorization.
	val wealthTypeName: String
)

/// Specifies the nature of a liability for Fiqh deduction purposes.
/// 
/// Most schools of Fiqh allow deducting immediate debts from zakatable wealth.
/// For long-term debts, modern consensus often restricts deduction to the upcoming year's payments.
@Serializable
enum class LiabilityType(val string: String) {
	/// Dayn al-Hal: Immediate debt due soon (fully deductible).
	@SerialName("immediate")
	Immediate("immediate"),
	/// Dayn al-Mu'ajjal: Long-term debt (e.g., mortgages, car loans).
	/// Only the current year's (12 months) payments are deductible to prevent
	/// zeroing out zakat liability with massive long-term principal.
	@SerialName("longTerm")
	LongTerm("longTerm"),
}

/// Represents a named liability that can be deducted from Zakat calculations.
/// 
/// # Example
/// ```rust
/// use zakat_core::types::Liability;
/// use rust_decimal_macros::dec;
/// 
/// let mortgage = Liability::new("Mortgage Payment", dec!(1500));
/// let credit_card = Liability::new("Credit Card", dec!(500));
/// ```
@Serializable
data class Liability (
	/// Description of the liability (e.g., "Credit Card", "Mortgage")
	val description: String,
	/// Amount of the liability (Total outstanding balance)
	val amount: string,
	/// Type of liability (Immediate vs LongTerm)
	val kind: LiabilityType? = null,
	/// For LongTerm debts: Monthly payment amount to calculate annual cap.
	val monthlyPayment: string? = null
)

/// Represents the age category of livestock for Zakat purposes.
/// 
/// These categories are based on the Hadith specification for camel and cattle ages.
@Serializable
enum class LivestockAge(val string: String) {
	/// Bint Makhad - 1-year female camel (just weaned)
	@SerialName("bintMakhad")
	BintMakhad("bintMakhad"),
	/// Bint Labun - 2-year female camel (mother nursing another)
	@SerialName("bintLabun")
	BintLabun("bintLabun"),
	/// Hiqqah - 3-year female camel (ready for breeding)
	@SerialName("hiqqah")
	Hiqqah("hiqqah"),
	/// Jaza'ah - 4-year female camel (mature)
	@SerialName("jazaah")
	Jazaah("jazaah"),
	/// Tabi - 1-year calf (male or female cow)
	@SerialName("tabi")
	Tabi("tabi"),
	/// Musinnah - 2-year cow (fully grown)
	@SerialName("musinnah")
	Musinnah("musinnah"),
	/// Generic sheep/goat (age not differentiated in Fiqh for payment)
	@SerialName("jadha")
	Jadha("jadha"),
}

/// Represents the kind of livestock for Zakat.
@Serializable
enum class LivestockKind(val string: String) {
	@SerialName("sheep")
	Sheep("sheep"),
	@SerialName("goat")
	Goat("goat"),
	@SerialName("cow")
	Cow("cow"),
	@SerialName("camel")
	Camel("camel"),
}

/// Represents a structured livestock payment item.
/// 
/// This struct enables frontends to translate livestock descriptions dynamically
/// instead of receiving pre-translated strings.
@Serializable
data class LivestockDueItem (
	/// Number of animals due
	val count: UInt,
	/// Age category of the animal
	val age: LivestockAge,
	/// Kind of animal
	val kind: LivestockKind
)

/// Networking configuration for external API calls
@Serializable
data class NetworkConfig (
	/// Optional direct IP for Binance API to bypass DNS issues.
	/// If None, standard DNS resolution is used.
	val binanceApiIp: String? = null,
	/// Request timeout in seconds. Default: 30.
	val timeoutSeconds: UInt
)

/// Nisab standard for calculating the Zakat threshold on monetary wealth.
/// - `Gold`: Use the gold Nisab (85g × gold_price).
/// - `Silver`: Use the silver Nisab (595g × silver_price).
/// - `LowerOfTwo`: Use the lower of gold or silver Nisab - most beneficial for the poor.
@Serializable
enum class NisabStandard(val string: String) {
	/// Use the gold Nisab (85g × gold_price)
	@SerialName("gold")
	Gold("gold"),
	/// Use the silver Nisab (595g × silver_price)
	@SerialName("silver")
	Silver("silver"),
	/// Use the lower of gold or silver Nisab - most beneficial for the poor
	@SerialName("lowerOfTwo")
	LowerOfTwo("lowerOfTwo"),
}

/// Global configuration for Zakat prices.
@Serializable
data class ZakatConfig (
	/// Current market price of Gold per gram.
	val goldPricePerGram: string,
	/// Current market price of Silver per gram.
	val silverPricePerGram: string,
	/// Price of Rice per kg (for Zakat Fitrah).
	val ricePricePerKg: string? = null,
	/// Price of Rice per liter (for Zakat Fitrah).
	val ricePricePerLiter: string? = null,
	/// Nisab standard to use for cash, business assets, and investments.
	/// Set automatically via `with_madhab()` or manually via `with_nisab_standard()`.
	val cashNisabStandard: NisabStandard,
	/// Override default Gold Nisab (default: 85g).
	val nisabGoldGrams: string? = null,
	/// Override default Silver Nisab (default: 595g).
	val nisabSilverGrams: string? = null,
	/// Override default Agriculture Nisab (default: 653kg).
	val nisabAgricultureKg: string? = null,
	/// Locale code for output formatting (e.g., "en-US", "ar-SA").
	/// Use `zakat-i18n` crate for full i18n support.
	val localeCode: String,
	/// Currency code (e.g., "USD", "SAR").
	val currencyCode: String,
	/// Network configuration for external API calls.
	val networking: NetworkConfig? = null,
	/// Validation mode controlling strictness of Fiqh compliance.
	/// Defaults to `Strict` for production use.
	val mode: ZakatMode? = null
)

/// Helper enum to categorize wealth types
@Serializable
sealed class WealthType {
	@Serializable
	@SerialName("fitrah")
	object Fitrah: WealthType()
	@Serializable
	@SerialName("gold")
	object Gold: WealthType()
	@Serializable
	@SerialName("silver")
	object Silver: WealthType()
	@Serializable
	@SerialName("business")
	object Business: WealthType()
	@Serializable
	@SerialName("agriculture")
	object Agriculture: WealthType()
	@Serializable
	@SerialName("livestock")
	object Livestock: WealthType()
	@Serializable
	@SerialName("income")
	object Income: WealthType()
	@Serializable
	@SerialName("investment")
	object Investment: WealthType()
	@Serializable
	@SerialName("mining")
	object Mining: WealthType()
	@Serializable
	@SerialName("rikaz")
	object Rikaz: WealthType()
	@Serializable
	@SerialName("other")
	data class Other(val content: String): WealthType()
}

/// Generated type representing the anonymous struct variant `Livestock` of the `PaymentPayload` Rust enum
@Serializable
data class PaymentPayloadLivestockInner (
	/// Structured list of animals due (preferred for i18n)
	val heads_due: List<LivestockDueItem>
)

/// Generated type representing the anonymous struct variant `Agriculture` of the `PaymentPayload` Rust enum
@Serializable
data class PaymentPayloadAgricultureInner (
	val harvest_weight: string,
	val irrigation_method: String,
	val crop_value: string
)

/// Represents the type of Zakat payment due.
/// 
/// This enum distinguishes between:
/// - **Monetary**: The default payment type, representing a currency value.
/// - **Livestock**: In-kind payment of specific animals with structured data for i18n.
/// Used when Zakat is due as heads of livestock rather than cash.
@Serializable
sealed class PaymentPayload {
	/// Currency-based Zakat payment (default for most wealth types).
	@Serializable
	@SerialName("monetary")
	data class Monetary(val content: Decimal): PaymentPayload()
	/// In-kind livestock payment specifying animal types and counts.
	@Serializable
	@SerialName("livestock")
	data class Livestock(val content: PaymentPayloadLivestockInner): PaymentPayload()
	/// In-kind agriculture payment specifying harvest details.
	@Serializable
	@SerialName("agriculture")
	data class Agriculture(val content: PaymentPayloadAgricultureInner): PaymentPayload()
}

/// Represents the Zakat recommendation status for an asset.
/// 
/// This enum provides nuanced guidance beyond binary Payable/Exempt:
/// - **Obligatory**: Zakat is mandatory (net assets ≥ Nisab, Hawl met).
/// - **Recommended**: Voluntary Sadaqah is encouraged (near Nisab, 90-100%).
/// - **None**: Far below Nisab threshold.
/// 
/// # Fiqh Principle
/// While Zakat is strictly obligatory only when conditions are met,
/// voluntary charity (Sadaqah) is always encouraged in Islam.
/// This recommendation helps users consider giving even when not obligated.
@Serializable
enum class ZakatRecommendation(val string: String) {
	/// Zakat is obligatory (standard Zakat).
	/// Net assets ≥ Nisab and Hawl is satisfied.
	@SerialName("obligatory")
	Obligatory("obligatory"),
	/// Voluntary Sadaqah is recommended.
	/// Net assets are between 90% and 100% of Nisab.
	/// This is NOT obligatory but spiritually encouraged.
	@SerialName("recommended")
	Recommended("recommended"),
	/// No recommendation - assets are far below Nisab.
	@SerialName("none")
	None("none"),
}

/// Represents the detailed breakdown of the Zakat calculation.
@Serializable
data class ZakatDetails (
	/// Total assets subject to Zakat calculation.
	val totalAssets: string,
	/// Liabilities that can be deducted from the total assets (Only debts due immediately).
	val liabilitiesDueNow: string,
	/// Named liabilities for granular tracking (v1.1+).
	/// When calculating net assets, both `liabilities_due_now` and this vector are summed.
	val liabilities: List<Liability>,
	/// Net assets after deducting liabilities (total_assets - liabilities_due_now).
	val netAssets: string,
	/// The Nisab threshold applicable for this type of wealth.
	val nisabThreshold: string,
	/// Whether Zakat is due (net_assets >= nisab_threshold).
	val isPayable: Boolean,
	/// The final Zakat amount due.
	val zakatDue: string,
	/// The type of wealth this calculation is for.
	val wealthType: WealthType,
	/// Reason for the status, if not payable (e.g. "Hawl not met").
	val statusReason: String? = null,
	/// Optional label for the asset (e.g. "Main Store", "Gold Necklace").
	val label: String? = null,
	/// Detailed payment payload (Monetary amount or specific assets like Livestock heads).
	val payload: PaymentPayload,
	/// Step-by-step trace of how this calculation was derived.
	val calculationTrace: CalculationTrace,
	/// Structured warnings about the calculation (v1.1+).
	val structuredWarnings: List<CalculationWarning>,
	/// Non-fatal warnings about the calculation (e.g., negative values clamped).
	val warnings: List<String>,
	/// Recommendation status (Feature 4: "Almost Payable" State).
	/// Indicates if voluntary Sadaqah is recommended even when Zakat is not obligatory.
	val recommendation: ZakatRecommendation? = null
)

/// Structured representation of a Zakat calculation for API consumers.
/// 
/// This struct allows frontend applications (e.g., React, Vue) to render their
/// own UI without parsing pre-formatted strings.
@Serializable
data class ZakatExplanation (
	/// Label of the asset (e.g., "Main Store", "Gold Necklace").
	val label: String,
	/// Type of wealth (e.g., "Gold", "Business").
	val wealthType: String,
	/// Status of the calculation: "Payable" or "Exempt".
	val status: String,
	/// The amount of Zakat due.
	val amountDue: string,
	/// Formatted total assets string.
	val formattedTotal: String,
	/// Formatted Zakat due string.
	val formattedDue: String,
	/// Progress towards Nisab threshold (0.0 to 1.0).
	val nisabProgress: Double,
	/// Currency code for the calculation.
	val currencyCode: String,
	/// Step-by-step calculation steps.
	val steps: List<CalculationStep>,
	/// Non-fatal warnings about the calculation.
	val warnings: List<String>,
	/// Additional notes (e.g., exemption reason).
	val notes: List<String>
)

/// Rules that govern Zakat calculations for a specific Madhab.
/// Contains Nisab standard, jewelry exemption policy, and Zakat rates.
@Serializable
data class ZakatRules (
	/// The Nisab standard to use for determining Zakat eligibility.
	val nisabStandard: NisabStandard,
	/// Whether personal jewelry is exempt from Zakat.
	val jewelryExempt: Boolean,
	/// Zakat rate for trade goods (default: 2.5% = 0.025).
	val tradeGoodsRate: string
)

/// Islamic school of thought (Madhab) for Zakat calculation.
/// Each Madhab has different rules regarding Nisab standards and jewelry exemptions.
@Serializable
enum class Madhab(val string: String) {
	/// Hanafi Madhab - Uses LowerOfTwo Nisab standard, jewelry is zakatable.
	@SerialName("hanafi")
	Hanafi("hanafi"),
	/// Shafi'i Madhab - Uses Gold Nisab standard, personal jewelry is exempt.
	@SerialName("shafi")
	Shafi("shafi"),
	/// Maliki Madhab - Uses Gold Nisab standard, personal jewelry is exempt.
	@SerialName("maliki")
	Maliki("maliki"),
	/// Hanbali Madhab - Uses LowerOfTwo Nisab standard, personal jewelry is exempt.
	@SerialName("hanbali")
	Hanbali("hanbali"),
}

/// A wrapper enum for all zakatable asset types.
/// This enables serialization and uniform handling in a portfolio.
/// 
/// Each variant represents a different category of zakatable wealth:
/// - `Business`: Trade goods and business assets (Urud al-Tijarah).
/// - `Income`: Professional income (Zakat al-Mustafad).
/// - `Livestock`: Animals (camels, cattle, sheep/goats).
/// - `Agriculture`: Crops and harvests.
/// - `Investment`: Stocks, crypto, and mutual funds.
/// - `Mining`: Mineral extraction (Ma'dan).
/// - `PreciousMetals`: Gold and silver.
/// - `Fitrah`: Zakat al-Fitr (obligatory charity at end of Ramadan).
/// - `Custom`: User-defined assets with custom rules.
/// 
/// Note: The `Ledger` variant is provided by the `zakat-ledger` crate.
/// When using the full zakat crate (facade), you can use `ExtendedPortfolioItem`
/// which includes ledger assets.
@Serializable
sealed class PortfolioItem {
	/// Business assets (cash, inventory, receivables).
	@Serializable
	@SerialName("business")
	data class Business(val data: BusinessZakat): PortfolioItem()
	/// Professional income (salary, freelance earnings).
	@Serializable
	@SerialName("income")
	data class Income(val data: IncomeZakatCalculator): PortfolioItem()
	/// Livestock assets (camels, cattle, sheep, goats).
	@Serializable
	@SerialName("livestock")
	data class Livestock(val data: LivestockAssets): PortfolioItem()
	/// Agricultural assets (crops, harvests).
	@Serializable
	@SerialName("agriculture")
	data class Agriculture(val data: AgricultureAssets): PortfolioItem()
	/// Investment assets (stocks, crypto, mutual funds).
	@Serializable
	@SerialName("investment")
	data class Investment(val data: InvestmentAssets): PortfolioItem()
	/// Mining assets (minerals, extracted resources).
	@Serializable
	@SerialName("mining")
	data class Mining(val data: MiningAssets): PortfolioItem()
	/// Precious metals (gold, silver).
	@Serializable
	@SerialName("preciousMetals")
	data class PreciousMetals(val data: PreciousMetals): PortfolioItem()
	/// Zakat al-Fitr calculator.
	@Serializable
	@SerialName("fitrah")
	data class Fitrah(val data: FitrahCalculator): PortfolioItem()
	/// User-defined custom assets.
	@Serializable
	@SerialName("custom")
	data class Custom(val data: CustomAsset): PortfolioItem()
}

