// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartBusiness>>
abstract class DartBusiness implements RustOpaqueInterface {
  /// Calculate Zakat for this asset.
  DartZakatResult calculate({required DartZakatConfig config});

  ///Set the `cash` field.
  void cash({required FrbDecimal value});

  ///Set the `debt` field.
  void debt({required FrbDecimal value});

  static Future<DartBusiness> default_() =>
      RustLib.instance.api.crateApiAssetsDartBusinessDefault();

  /// Get the asset ID.
  String getId();

  /// Get the asset label.
  String? getLabel();

  ///Set the `hawl` field.
  void hawl({required bool value});

  ///Set the `inventory` field.
  void inventory({required FrbDecimal value});

  ///Set the `label` field.
  void label({required String value});

  /// Create a new instance with default values.
  factory DartBusiness() =>
      RustLib.instance.api.crateApiAssetsDartBusinessNew();

  ///Set the `receivables` field.
  void receivables({required FrbDecimal value});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartIncome>>
abstract class DartIncome implements RustOpaqueInterface {
  /// Calculate Zakat for this asset.
  DartZakatResult calculate({required DartZakatConfig config});

  ///Set the `debt` field.
  void debt({required FrbDecimal value});

  static Future<DartIncome> default_() =>
      RustLib.instance.api.crateApiAssetsDartIncomeDefault();

  ///Set the `expenses` field.
  void expenses({required FrbDecimal value});

  /// Get the asset ID.
  String getId();

  /// Get the asset label.
  String? getLabel();

  ///Set the `hawl` field.
  void hawl({required bool value});

  ///Set the `income` field.
  void income({required FrbDecimal value});

  ///Set the `label` field.
  void label({required String value});

  /// Create a new instance with default values.
  factory DartIncome() => RustLib.instance.api.crateApiAssetsDartIncomeNew();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartInvestment>>
abstract class DartInvestment implements RustOpaqueInterface {
  /// Calculate Zakat for this asset.
  DartZakatResult calculate({required DartZakatConfig config});

  ///Set the `debt` field.
  void debt({required FrbDecimal value});

  static Future<DartInvestment> default_() =>
      RustLib.instance.api.crateApiAssetsDartInvestmentDefault();

  /// Get the asset ID.
  String getId();

  /// Get the asset label.
  String? getLabel();

  ///Set the `hawl` field.
  void hawl({required bool value});

  ///Set the `label` field.
  void label({required String value});

  /// Create a new instance with default values.
  factory DartInvestment() =>
      RustLib.instance.api.crateApiAssetsDartInvestmentNew();

  ///Set the `value` field.
  void value({required FrbDecimal value});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartMining>>
abstract class DartMining implements RustOpaqueInterface {
  /// Calculate Zakat for this asset.
  DartZakatResult calculate({required DartZakatConfig config});

  ///Set the `debt` field.
  void debt({required FrbDecimal value});

  static Future<DartMining> default_() =>
      RustLib.instance.api.crateApiAssetsDartMiningDefault();

  /// Get the asset ID.
  String getId();

  /// Get the asset label.
  String? getLabel();

  ///Set the `hawl` field.
  void hawl({required bool value});

  ///Set the `label` field.
  void label({required String value});

  /// Create a new instance with default values.
  factory DartMining() => RustLib.instance.api.crateApiAssetsDartMiningNew();

  ///Set the `value` field.
  void value({required FrbDecimal value});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartPreciousMetals>>
abstract class DartPreciousMetals implements RustOpaqueInterface {
  /// Calculate Zakat for this precious metal.
  DartZakatResult calculate({required DartZakatConfig config});

  /// Set liabilities to deduct.
  void debt({required FrbDecimal amount});

  static Future<DartPreciousMetals> default_() =>
      RustLib.instance.api.crateApiAssetsDartPreciousMetalsDefault();

  /// Get the asset ID.
  String getId();

  /// Get the asset label.
  String? getLabel();

  /// Create a new gold asset.
  static DartPreciousMetals gold({required FrbDecimal weightGrams}) => RustLib
      .instance
      .api
      .crateApiAssetsDartPreciousMetalsGold(weightGrams: weightGrams);

  /// Set whether Hawl (1 lunar year) is satisfied.
  void hawl({required bool satisfied});

  /// Set the asset label.
  void label({required String label});

  /// Set the purity (karat for gold 1-24, or per-mille for silver 1-1000).
  void purity({required int value});

  /// Create a new silver asset.
  static DartPreciousMetals silver({required FrbDecimal weightGrams}) => RustLib
      .instance
      .api
      .crateApiAssetsDartPreciousMetalsSilver(weightGrams: weightGrams);

  /// Set the weight in grams.
  void weight({required FrbDecimal grams});
}
