// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_core`, `from_core`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartZakatConfig>>
abstract class DartZakatConfig implements RustOpaqueInterface {
  /// Get the gold nisab threshold in currency.
  FrbDecimal goldNisab();

  /// Get the monetary nisab threshold (lower of gold/silver).
  FrbDecimal monetaryNisab();

  /// Create a new configuration with required parameters.
  factory DartZakatConfig({
    required FrbDecimal goldPrice,
    required FrbDecimal silverPrice,
    required String madhab,
  }) => RustLib.instance.api.crateApiTypesDartZakatConfigNew(
    goldPrice: goldPrice,
    silverPrice: silverPrice,
    madhab: madhab,
  );

  /// Get the silver nisab threshold in currency.
  FrbDecimal silverNisab();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< DartZakatResult>>
abstract class DartZakatResult implements RustOpaqueInterface {
  List<DartCalculationStep> get calculationTrace;

  bool get isPayable;

  String? get label;

  FrbDecimal get netAssets;

  FrbDecimal get nisabThreshold;

  String? get statusReason;

  FrbDecimal get totalAssets;

  List<String> get warnings;

  String get wealthType;

  FrbDecimal get zakatDue;

  set calculationTrace(List<DartCalculationStep> calculationTrace);

  set isPayable(bool isPayable);

  set label(String? label);

  set netAssets(FrbDecimal netAssets);

  set nisabThreshold(FrbDecimal nisabThreshold);

  set statusReason(String? statusReason);

  set totalAssets(FrbDecimal totalAssets);

  set warnings(List<String> warnings);

  set wealthType(String wealthType);

  set zakatDue(FrbDecimal zakatDue);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrbDecimal>>
abstract class FrbDecimal implements RustOpaqueInterface {
  /// Create from integer value.
  static FrbDecimal fromInt({required PlatformInt64 val}) =>
      RustLib.instance.api.crateApiTypesFrbDecimalFromInt(val: val);

  /// Create from string representation (most precise).
  static FrbDecimal fromString({required String s}) =>
      RustLib.instance.api.crateApiTypesFrbDecimalFromString(s: s);

  /// Check if value is positive.
  bool isPositive();

  /// Check if value is zero.
  bool isZero();

  /// Convert to f64 (may lose precision - use only for display).
  double toF64();

  /// Convert to string representation.
  @override
  String toString();

  /// Create zero value.
  static FrbDecimal zero() =>
      RustLib.instance.api.crateApiTypesFrbDecimalZero();
}

/// A single step in the calculation trace.
class DartCalculationStep {
  /// The step key (for i18n).
  final String key;

  /// The description in English.
  final String description;

  /// The amount at this step (if applicable).
  final FrbDecimal? amount;

  /// The operation type.
  final String operation;

  const DartCalculationStep({
    required this.key,
    required this.description,
    this.amount,
    required this.operation,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      description.hashCode ^
      amount.hashCode ^
      operation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartCalculationStep &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          description == other.description &&
          amount == other.amount &&
          operation == other.operation;
}
