// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Validate if a string is a valid decimal format.
bool validateInputString({required String s}) =>
    RustLib.instance.api.crateApiZakatValidateInputString(s: s);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartPortfolioItem>>
abstract class DartPortfolioItem implements RustOpaqueInterface {
  String get id;

  bool get isPayable;

  String get label;

  String get wealthType;

  FrbDecimal get zakatDue;

  set id(String id);

  set isPayable(bool isPayable);

  set label(String label);

  set wealthType(String wealthType);

  set zakatDue(FrbDecimal zakatDue);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartPortfolioResult>>
abstract class DartPortfolioResult implements RustOpaqueInterface {
  bool get isPayable;

  int get itemsCount;

  FrbDecimal get nisabThreshold;

  String get status;

  FrbDecimal get totalAssets;

  FrbDecimal get totalZakatDue;

  set isPayable(bool isPayable);

  set itemsCount(int itemsCount);

  set nisabThreshold(FrbDecimal nisabThreshold);

  set status(String status);

  set totalAssets(FrbDecimal totalAssets);

  set totalZakatDue(FrbDecimal totalZakatDue);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NativePortfolio>>
abstract class NativePortfolio implements RustOpaqueInterface {
  /// Adds a business asset to the portfolio.
  /// Returns the UUID of the added asset.
  String addBusiness({
    required FrbDecimal cash,
    required FrbDecimal inventory,
    required FrbDecimal receivables,
    required FrbDecimal liabilities,
    required String label,
  });

  /// Adds gold asset to the portfolio.
  /// Returns the UUID of the added asset.
  String addGold({
    required FrbDecimal weightGrams,
    required int purityKarat,
    required String label,
  });

  /// Adds savings/cash asset to the portfolio.
  /// Returns the UUID of the added asset.
  String addSavings({
    required FrbDecimal cashInHand,
    required FrbDecimal bankBalance,
    required String label,
  });

  /// Adds silver asset to the portfolio.
  /// Returns the UUID of the added asset.
  String addSilver({
    required FrbDecimal weightGrams,
    required int purityPerThousand,
    required String label,
  });

  /// Calculates total Zakat due across all portfolio items.
  DartPortfolioResult calculate();

  /// Clears all items from the portfolio.
  void clear();

  /// Gets individual results for each portfolio item.
  List<DartPortfolioItem> getItemResults();

  /// Returns the number of items in the portfolio.
  int itemCount();

  /// Creates a new NativePortfolio with the specified configuration.
  factory NativePortfolio({
    required FrbDecimal goldPrice,
    required FrbDecimal silverPrice,
    required String madhab,
  }) => RustLib.instance.api.crateApiZakatNativePortfolioNew(
    goldPrice: goldPrice,
    silverPrice: silverPrice,
    madhab: madhab,
  );

  /// Removes an asset from the portfolio by its UUID.
  bool removeItem({required String id});
}
