/// Zakat Dart FFI Library
///
/// This crate provides Flutter Rust Bridge bindings for the Zakat library.
/// 
/// # Architecture
/// 
/// ```text
/// ┌─────────────────────────────────────────┐
/// │ Dart/Flutter App                        │
/// └─────────────────────────────────────────┘
///                    ↓ FFI
/// ┌─────────────────────────────────────────┐
/// │ rust_lib_zakat_dart (this crate)        │
/// │   - api/types.rs    → FrbDecimal, etc.  │
/// │   - api/assets.rs   → DartBusiness, ... │
/// │   - api/zakat.rs    → NativePortfolio   │
/// └─────────────────────────────────────────┘
///                    ↓ imports
/// ┌─────────────────────────────────────────┐
/// │ zakat (core library)                    │
/// └─────────────────────────────────────────┘
/// ```

// Macros for generating Dart wrappers
#[macro_use]
mod macros;

// API modules exposed to Flutter Rust Bridge
pub mod api;

// Generated by flutter_rust_bridge
mod frb_generated;
